//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Client
    {
        [Key]
        public Guid Id { get; set; }
        public string Name { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0: ## ####-##-##}")]
        public string Phone { get; set; }
        public string Gender { get; set; }
        [Display(Name = "Last Purchase")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString ="{0: dd/MM/yyyy}")]
        public Nullable<DateTime> LastPurchase { get; set; }
        public string Address { get; set; }
        public string Occupation { get; set; }
        
        public Region Region { get; set; }
        public Classification Classification { get; set; }
        public AspNetUsers Seller { get; set; }

        public ICollection<User> Sellers { get; set; }
        public ICollection<Region> Regions { get; set; }
        public ICollection<Classification> Classifications { get; set; }


    }
}
